### ISSUE TITLE
Complement README.md

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/Moisture_tracking_intercomparison#24]
What do we need to add?

- goal of this repository?
- .?

Please add ideas to this issue

**Comment by Peter9192** [comment]
Maybe point to the contributing guidelines?

**Comment by chrisweij** [comment]
Yes, I added that the Readme file now.

**Comment by ruudvdent** [comment]
@chrisweij , can we close this issue for now then?

**Comment by chrisweij** [comment]
@ruudvdent I think it is not merged yet (and it should probably be updated with the new analysis)
