### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/Moisture_tracking_intercomparison#25]
Is everybody OK to have an Apache license?

**Comment by Peter9192** [comment]
Maybe let's go with Apache if no objections are raised here by the end of the week?

**Comment by chrisweij** [comment]
Nobody objected so I will close this for now.

**Comment by Peter9192** [comment]
Then we should add the license as well, right? :-)

**Comment by chrisweij** [comment]
@Peter9192 Good point, thanks. In the citation file it already mentioned that we are using the Apache 2.0 license so I thought we already did this. Will add this.

**Comment by chrisweij** [comment]
Should be closed when #76 is approved

**Comment by Peter9192** [comment]
If you add "closes #25" to the top post of #76, this issue will automatically be closed once that one is merged :-)
